package femi.core.utils;

public enum UserRoleType {
    CUSTOMER,
    CUSTOMER_ADMIN,
    PROVIDER_ADMIN,
    PROVIDER,
    PROVIDER_OTHER_ORG,
    PATIENT,
    C2P_PROVIDER,
    C2P_PROVIDER_OTHER_ORG,
    C2P_PROVIDER_DOCTOR_ONLINE,
    ADMIN,
    TMP_ADMIN,
    TMP_CLINICIAN
}
